CREATE DATABASE IF NOT EXISTS db_saude;
USE db_saude;

/* ---------------<TABELAS>-------------- */

CREATE TABLE IF NOT EXISTS TIPO_USUARIO(
	idTipoUsuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tipoUsuario VARCHAR(45)
)
ENGINE INNODB;

CREATE TABLE IF NOT EXISTS USUARIO(
	idUsuario INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nomeUsuario VARCHAR(100) NOT NULL UNIQUE,
    senhaUsuario VARCHAR(255),
    idTipoUsuario INT NOT NULL,
    CONSTRAINT idTipoUsuario
	 FOREIGN KEY (idTipoUsuario) REFERENCES TIPO_USUARIO(idTipoUsuario)
	 ON DELETE CASCADE
	 ON UPDATE NO ACTION
)
ENGINE INNODB;

CREATE TABLE IF NOT EXISTS HOSPITAL(
	idHospital INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nomeHospital VARCHAR(100) NOT NULL,
	ruaHospital VARCHAR(100) NOT NULL,
	bairroHospital VARCHAR(45) NOT NULL,
	cepHospital VARCHAR(9) NOT NULL,
    telefoneHospital VARCHAR(14),
	idUsuario INT NOT NULL,
    CONSTRAINT idUsuario
	 FOREIGN KEY (idUsuario) REFERENCES USUARIO(idUsuario)
	 ON DELETE CASCADE
	 ON UPDATE NO ACTION
)
ENGINE INNODB;

CREATE TABLE IF NOT EXISTS PACIENTE(
	idPaciente INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nomePaciente VARCHAR(100) NOT NULL,
    ruaPaciente	VARCHAR(100) NOT NULL,
    numeroSUS VARCHAR(15) NOT NULL,
    telefonePaciente VARCHAR(14) NOT NULL,
    bairroPaciente VARCHAR(45) NOT NULL,
    gravidade VARCHAR(45) NOT NULL
)
ENGINE INNODB;

CREATE TABLE IF NOT EXISTS TIPO_UNIDADE(
	idTipoUnidade INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    tipoUnidade VARCHAR(50) NOT NULL
)
ENGINE INNODB;

CREATE TABLE IF NOT EXISTS ESPECIALIDADE(
	idEspecialidade INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	tipoEspecialidade VARCHAR(45) NOT NULL UNIQUE
)
ENGINE INNODB;

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR(13) NOT NULL PRIMARY KEY,
    nomeMedico VARCHAR(45) NOT NULL,
    idEspecialidade INT NOT NULL,
    CONSTRAINT idEspecialidade
	 FOREIGN KEY (idEspecialidade) REFERENCES ESPECIALIDADE(idEspecialidade)
	 ON DELETE CASCADE
	 ON UPDATE NO ACTION
)
ENGINE INNODB;

CREATE TABLE IF NOT EXISTS UNIDADE_SAUDE(
	idUnidadeSaude INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nomeUnidadeSaude VARCHAR(45) NOT NULL,
    ruaUnidadeSaude VARCHAR(100) NOT NULL,
    bairroUnidadeSaude VARCHAR(45) NOT NULL,
    telefoneUnidadeSaude VARCHAR(14) NOT NULL,
    vagas INT,
    idTipoUnidade INT NOT NULL,
    CONSTRAINT idTipoUnidade
	 FOREIGN KEY (idTipoUnidade) REFERENCES TIPO_UNIDADE (idTipoUnidade)
	 ON DELETE CASCADE
	 ON UPDATE NO ACTION
)
ENGINE INNODB;

CREATE TABLE IF NOT EXISTS MEDICO_ATENDE_UNIDADE(
	idAtendimento INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	horarioMedico DATETIME NOT NULL,
    idUnidadeSaude INT NOT NULL, 
    CRM VARCHAR(13) NOT NULL,
    CONSTRAINT idUnidadeSaude
	 FOREIGN KEY (idUnidadeSaude) REFERENCES UNIDADE_SAUDE(idUnidadeSaude)
	 ON DELETE CASCADE
	 ON UPDATE NO ACTION,
	CONSTRAINT CRM
	 FOREIGN KEY (CRM) REFERENCES MEDICO(CRM)
	 ON DELETE CASCADE
	 ON UPDATE NO ACTION
)
ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS ENCAMINHAMENTO(
	idEncaminhamento INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    situacao VARCHAR(20),
    idAtendimento INT NOT NULL,
    idUnidadeSaude INT NOT NULL,
    idPaciente INT NOT NULL,
    idHospital INT NOT NULL, 
	idUsuario INT NOT NULL,
    CONSTRAINT idAtendimento_Esc
	 FOREIGN KEY (idAtendimento) REFERENCES MEDICO_ATENDE_UNIDADE(idAtendimento)
	 ON DELETE CASCADE
	 ON UPDATE NO ACTION,
    CONSTRAINT idUnidadeSaude_Enc
	 FOREIGN KEY (idUnidadeSaude) REFERENCES UNIDADE_SAUDE(idUnidadeSaude)
	 ON DELETE CASCADE
	 ON UPDATE NO ACTION,
    CONSTRAINT idPaciente_Enc
	 FOREIGN KEY (idPaciente) REFERENCES PACIENTE(idPaciente)
	 ON DELETE CASCADE
	 ON UPDATE NO ACTION,
    CONSTRAINT idHospital_Enc
	 FOREIGN KEY (idHospital) REFERENCES HOSPITAL(idHospital)
	 ON DELETE CASCADE
	 ON UPDATE NO ACTION,
    CONSTRAINT idUsuario_Enc
	 FOREIGN KEY (idUsuario) REFERENCES USUARIO(idUsuario)
	 ON DELETE CASCADE
	 ON UPDATE NO ACTION
)
ENGINE = INNODB;

INSERT INTO TIPO_USUARIO VALUES (NULL, 'usuario-hospital');
INSERT INTO USUARIO VALUES (NULL, 'Administrador', 'admin', 1);

SELECT `PACIENTE`.`idPaciente`, `UNIDADE_SAUDE`.`idUnidadeSaude`, `PACIENTE`.`nomePaciente`, 
`UNIDADE_SAUDE`.`nomeUnidadeSaude`, `MEDICO_ATENDE_UNIDADE`.`idAtendimento`, 
DATE_FORMAT(`MEDICO_ATENDE_UNIDADE`.`horarioMedico`, '%d/%m/%Y %H:%i') as horarioMedico
FROM ENCAMINHAMENTO
INNER JOIN UNIDADE_SAUDE ON (`ENCAMINHAMENTO`.`idUnidadeSaude` = `UNIDADE_SAUDE`.`idUnidadeSaude`)
INNER JOIN MEDICO_ATENDE_UNIDADE ON (`ENCAMINHAMENTO`.`idAtendimento` = `MEDICO_ATENDE_UNIDADE`.`idAtendimento`)
INNER JOIN PACIENTE ON (`ENCAMINHAMENTO`.`idPaciente` = `PACIENTE`.`idPaciente`)
WHERE idEncaminhamento = 19